[package]
name = "simpleicp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kd-tree = "0.5.0"
ndarray = "0.15.6"
typenum = "1.16.0"